version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgres://iam:iam@db:5432/iam?sslmode=disable
      - REDIS_URL=redis:6379
      - ENV=development
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8080

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: iam
      POSTGRES_PASSWORD: iam
      POSTGRES_DB: iam
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata:
